export const DataLeft = [
    {
        name:"Temperature & Humidity Sensors",
        image:"assets/images/img1.png"
    },
    {
        name:"Smart office",
        image:"assets/images/img2.png"
    },
    {
        name:"Fleet tracking",
        image:"assets/images/img3.png"
    },
    {
        name:"Fuel Level Monitoring",
        image:"assets/images/img4.png"
    },
]

export const UserData = [
    {
        id: 1,
        name: "Jon Snow",
        time: "2024-08-23 23:43:06",
        email: "jonsnow@gmail.com",
        Description: "Autogenerated Tenant Administrators group with all permissions.",
      },
      {
        id: 2,
        name: "Daenerys Targaryen",
        time: "2024-08-24 10:15:32",
        email: "daenerys@gmail.com",
        Description: "Autogenerated Superuser group with elevated permissions.",
      },
      {
        id: 3,
        name: "Arya Stark",
        time: "2024-08-25 14:20:11",
        email: "arya.stark@gmail.com",
        Description: "Autogenerated Read-Only group with view permissions only.",
      },
      {
        id: 4,
        name: "Tyrion Lannister",
        time: "2024-08-26 09:35:47",
        email: "tyrion.lannister@gmail.com",
        Description: "Autogenerated Power Users group with advanced permissions.",
      },
      {
        id: 5,
        name: "Sansa Stark",
        time: "2024-08-27 12:45:22",
        email: "sansa.stark@gmail.com",
        Description: "Autogenerated Tenant Managers group with managerial permissions.",
      },
      {
        id: 6,
        name: "Bran Stark",
        time: "2024-08-28 15:30:06",
        email: "bran.stark@gmail.com",
        Description: "Autogenerated Data Analysts group with access to reporting tools.",
      },
  ];

// export const userData (){

// }